### ISSUE TITLE
AttributeError가 뜹니다.

### ISSUE THREAD

**Issue by loveAlakazam** [chandong83/snowboy_wrapper#1]
안녕하세요?  snowboy_wrapper을 다운받고 
readme에 있는requirement 대로 명령어 쳐서 설치했습니다.
그리고 python example.py를 해봤는데
동작 오류 에러메시지는 다음과 같습니다.
Traceback (most recent call last):
 File "example.py", line 34, in <module>
   if snow.isListening()== False:
 File "/home/pi/snowboy_wrapper/triggerword/snowboy.py", line 40, in isListening
  return self.detector.isListening()
 File "/home/pi/snowboy_wrapper/triggerword/snowboydecoder.py", line 198 in isListening
  return self.ReadyToListening
AttributeError: 'HotwordDetector' object has no attribute 'ReadyToListening'
 
이러한 AttributeError은 구글링결과 '모듈의 함수나 변수를 잘못 입력했을 때 발생'한다고 하는데요...
제가보기에는 완전해보이는데 뭐가 문제인지 모르겠습니다...ㅠ

**Comment by chandong83** [comment]
안녕하세요. 혹시 라즈베리파이 OS 버전과 파이썬 버전을 좀 알 수 있을까요?
OS 버전은 
$ lsb_release -a
파이썬 버전은
$ python --version
으로 확인이 가능합니다.

**Comment by loveAlakazam** [comment]
앗 감사합니다!
라즈베리파이의 OS버전은 Raspbian GNU/Linux9.4 (stretch) 
파이썬 버전은 Python 2.7.13
파이썬3버전은 Python 3.5.3
입니다.

**Comment by chandong83** [comment]
흠... 이상하네요;;; 혹시 라즈베리파이 하드웨어도 알 수 있을까요?

**Comment by loveAlakazam** [comment]
라즈베리파이 3  b입니다..
